---
- name: Download postgres repository key
  command: "wget https://www.postgresql.org/media/keys/ACCC4CF8.asc"
  args:
    chdir: /tmp/
    creates: /tmp/ACCC4CF8.asc
    warn: false

- name: Install postgres repository key
  command: "apt-key add /tmp/ACCC4CF8.asc"
  changed_when: false

## The above 3 tasks are crappy work-arounds - ansible has a module for this, but the python 
## modules they use are *extremely* delicate about SSL certificates and prone to breaking 
## unexpectedly. 

- name: Add postgres apt repository 
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main'
    state: present
    update_cache: yes

- name: Ensure packages are installed
  apt: 
    name: "{{item}}"
  with_items:
    - postgresql-{{ postgres_version }}
    - libpq-dev
    - python-psycopg2

- name: Enable and start postgres service
  service:
    name: postgresql
    enabled: yes
    state: started

# vim:ft=ansible:
